# Config file for the acts_as_solr plugin.
#
# If you change the host or port number here, make sure you update 
# them in your Solr config file

# config for stg should be moved to localhost
stg:
  url: http://webqa1a.olcc.lan:8983/solr
  base: webqa1a.olcc.lan
  port: 8983
  path: solr

stg_dply:
  url: http://webqa1a.olcc.lan:8983/solr
  base: webqa1a.olcc.lan
  port: 8983
  path: solr
  
development:
  url: http://10.10.64.121:8983/solr
  base: 10.10.64.121
  port: 8983
  path: solr


development_dply:
  url: http://127.0.0.1:8983/solr
  base: 127.0.0.1
  port: 8983
  path: solr

adam:
  #uat
#  url: http://10.10.64.122:8982/solr
#  base: 10.10.64.122
#  port: 8982
  #dev
  url: http://10.10.64.121:8983/solr
  base: 10.10.64.121
  #localhost
#  url: http://127.0.0.1:8983/solr
#  base: 127.0.0.1
  #qa
#  url: http://webqa1a.olcc.lan:8983/solr
#  base: webqa1a.olcc.lan
  port: 8983
  path: solr

staging:
  url: http://127.0.0.1:8982/solr
  base: 127.0.0.1
  port: 8982
  path: solr

qa:
  url: http://127.0.0.1:8983/solr
  base: 127.0.0.1
  port: 8983
  path: solr

qa_etl:
  url: http://127.0.0.1:8983/solr
  base: 127.0.0.1
  port: 8983
  path: solr

qa_dply:
  url: http://127.0.0.1:8983/solr
  base: 127.0.0.1
  port: 8983
  path: solr

uat:
  url: http://127.0.0.1:8982/solr
  base: 127.0.0.1
  port: 8982
  path: solr

uat_etl:
  url: http://127.0.0.1:8982/solr
  base: 127.0.0.1
  port: 8982
  path: solr

uat_dply:
  url: http://127.0.0.1:8982/solr
  base: 127.0.0.1
  port: 8982
  path: solr
  
production:
  url: http://127.0.0.1:8983/solr
  base: 127.0.0.1
  port: 8983
  path: solr

etl:
  url: http://solr.olcc.lan:8983/solrprd
  base: solr.olcc.lan
  port: 8983
  path: solrprd

test:
  url: http://127.0.0.1:8983/solr
  base: solr.olcc.lan
  port: 8982
  path: solr
